from tkinter import *
from 
root = Tk()
menubar= Menu(root)
filemenu= Menu(menubar, tearoff=0)
filemenu.add_command(label="New" )
filemenu.add_command(label="Open")
filemenu.add_command(label="Save")
filemenu.add_command(label="Close")
menubar.add_cascade(label="File" ,menu=filemenu)

editmenu = Menu(menubar, tearoff=0)
editmenu.add_command(label="Undo")
editmenu.add_command(label="Cut")
editmenu.add_command(label="Copy")
editmenu.add_command(label="Paste")
editmenu.add_command(label="Select All")
menubar.add_cascade(label="Edit", menu=editmenu)

font = Menu(menubar, tearoff=0)
font.add_command(label="Color")
font.add_command(label="Style")
font.add_command(label="Bold")
menubar.add_cascade(label="Font", menu=font)

exitmanu=Menu(menubar,tearoff=0)
exitmanu.add_command(label="Exit",command=root.quit)
menubar.add_cascade(label="Exit",menu=exitmanu)
root.config(menu=menubar)
root.mainloop()